import 'reflect-metadata';

export const CONTROLLER_METADATA = 'CONTROLLER_METADATA';
export const ROUTE_METADATA = 'ROUTE_METADATA';
export const INJECTABLE_METADATA = 'INJECTABLE_METADATA';

export function Injectable(): ClassDecorator {
    return (target: any) => {
        Reflect.defineMetadata(INJECTABLE_METADATA, true, target);
    };
}

export function Controller(prefix: string = ''): ClassDecorator {
    return (target: any) => {
        Reflect.defineMetadata(CONTROLLER_METADATA, prefix, target);
        // Controllers are automatically considered injectable
        Reflect.defineMetadata(INJECTABLE_METADATA, true, target);
    };
}

export interface RouteDefinition {
    path: string;
    method: 'get' | 'post' | 'put' | 'delete' | 'patch' | 'head' | 'options';
    methodName: string | symbol;
}

function createRouteDecorator(method: string) {
    return (path: string = '/'): MethodDecorator => {
        return (target: any, propertyKey: string | symbol, descriptor: PropertyDescriptor) => {
            console.log(`@${method} called for ${String(propertyKey)}`);
            if (!Reflect.hasMetadata(ROUTE_METADATA, target.constructor)) {
                Reflect.defineMetadata(ROUTE_METADATA, [], target.constructor);
            }
            const routes = Reflect.getMetadata(ROUTE_METADATA, target.constructor) as RouteDefinition[];
            routes.push({
                method: method as any,
                path,
                methodName: propertyKey,
            });
            Reflect.defineMetadata(ROUTE_METADATA, routes, target.constructor);
        };
    };
}


export const MIDDLEWARE_METADATA = 'MIDDLEWARE_METADATA';

export function Use(...middlewares: Function[]): ClassDecorator & MethodDecorator {
    return (target: any, propertyKey?: string | symbol, descriptor?: PropertyDescriptor) => {
        try {
            console.log(`@Use called for ${String(propertyKey || target.name)}`);
            if (propertyKey) {
                 // Method decorator
                 // target is prototype for instance members
                if (!Reflect.hasMetadata(MIDDLEWARE_METADATA, target, propertyKey)) {
                    Reflect.defineMetadata(MIDDLEWARE_METADATA, [], target, propertyKey);
                }
                const existing = Reflect.getMetadata(MIDDLEWARE_METADATA, target, propertyKey) as Function[];
                Reflect.defineMetadata(MIDDLEWARE_METADATA, [...existing, ...middlewares], target, propertyKey);
            } else {
                // Class decorator
                if (!Reflect.hasMetadata(MIDDLEWARE_METADATA, target)) {
                    Reflect.defineMetadata(MIDDLEWARE_METADATA, [], target);
                }
                const existing = Reflect.getMetadata(MIDDLEWARE_METADATA, target) as Function[];
                Reflect.defineMetadata(MIDDLEWARE_METADATA, [...existing, ...middlewares], target);
            }
        } catch (e) {
            console.error(`Error in @Use decorator:`, e);
            throw e;
        }
    };
}

export const Get = createRouteDecorator('get');
export const Post = createRouteDecorator('post');
export const Put = createRouteDecorator('put');
export const Delete = createRouteDecorator('delete');
export const Patch = createRouteDecorator('patch');
export const Head = createRouteDecorator('head');
export const Options = createRouteDecorator('options');

export const PARAM_METADATA = 'PARAM_METADATA';

export interface ParamDefinition {
    index: number;
    type: 'param' | 'query' | 'body' | 'ctx' | 'cookie';
    name?: string;
    designType?: any;
}

function createParamDecorator(type: 'param' | 'query' | 'body' | 'ctx' | 'cookie') {
    return (name?: string): ParameterDecorator => {
        return (target: Object, propertyKey: string | symbol | undefined, parameterIndex: number) => {
            if (!propertyKey) return;
            const params: ParamDefinition[] = Reflect.getOwnMetadata(PARAM_METADATA, target, propertyKey) || [];
            
            // Extract the strong type info. "design:paramtypes" is generated by TS when emitDecoratorMetadata is true.
            const designTypes = Reflect.getMetadata('design:paramtypes', target, propertyKey);
            const designType = designTypes ? designTypes[parameterIndex] : undefined;

            params.push({
                index: parameterIndex,
                type,
                name,
                designType
            });
            Reflect.defineMetadata(PARAM_METADATA, params, target, propertyKey);
        };
    };
}

export const Param = createParamDecorator('param');
export const Query = createParamDecorator('query');
export const Body = createParamDecorator('body');
export const Cookie = createParamDecorator('cookie');
export const Ctx = () => createParamDecorator('ctx')();

// --- WebSocket Decorators ---
export const WS_CONTROLLER_METADATA = 'WS_CONTROLLER_METADATA';
export const WS_ON_OPEN_METADATA = 'WS_ON_OPEN_METADATA';
export const WS_ON_MESSAGE_METADATA = 'WS_ON_MESSAGE_METADATA';
export const WS_ON_CLOSE_METADATA = 'WS_ON_CLOSE_METADATA';
export const WS_ON_DRAIN_METADATA = 'WS_ON_DRAIN_METADATA';

export function WebSocketController(path: string = '/*'): ClassDecorator {
    return (target: any) => {
        Reflect.defineMetadata(WS_CONTROLLER_METADATA, path, target);
        // WS Controllers are also injectable
        Reflect.defineMetadata(INJECTABLE_METADATA, true, target);
    };
}

function createWsMethodDecorator(metadataKey: string): MethodDecorator {
    return (target: any, propertyKey: string | symbol) => {
        Reflect.defineMetadata(metadataKey, propertyKey, target.constructor);
    };
}

export const OnOpen = () => createWsMethodDecorator(WS_ON_OPEN_METADATA);
export const OnMessage = () => createWsMethodDecorator(WS_ON_MESSAGE_METADATA);
export const OnClose = () => createWsMethodDecorator(WS_ON_CLOSE_METADATA);
export const OnDrain = () => createWsMethodDecorator(WS_ON_DRAIN_METADATA);

